# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.5.0-node-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --deployment

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

  check:
    docker:
      - image: circleci/ruby:2.5.0-node-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: bundle install --jobs=4 --retry=3 --deployment

      - run: bundle exec rubocop -D -R -fp -fh -o /tmp/test-results/rubocop.html

      - store_artifacts:
          path: /tmp/test-results
          destination: test-results


  rspec:
    docker:
      - image: circleci/ruby:2.5.0-node-browsers
        environment:
          DATABASE_URL: mysql2://root:@127.0.0.1:3306/circle_test

      - image: circleci/mysql:5.7-ram
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: circle_test

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --deployment

      - run:
          name: Install System Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y libappindicator1 fonts-liberation
            export CHROME_BIN=/usr/bin/google-chrome
            wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo dpkg -i google-chrome*.deb

      - run: RAILS_ENV=test bundle exec rake db:create db:schema:load
      - run: yarn install --frozen-lockfile
      - run: bundle exec rake assets:precompile
      - run: bundle exec webpack

      - run:
          name: run tests
          command: |
            mkdir -p /tmp/test-results
            RAILS_ENV=test bundle exec rspec --format progress \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml \
                            --format progress \
                            spec/

      - run: if [ -d tmp/screenshots ]; then cp -rf tmp/screenshots /tmp/test-results/ ; fi

      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

      - store_test_results:
          path: /tmp/test-results


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - check:
          requires:
            - build
      - rspec:
          requires:
            - build
